# Generated by Django 3.2.7 on 2021-09-23 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_description_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='list',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.tasks'),
        ),
    ]
